// <auto-generated />
namespace T4c.Corretora.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ajust : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ajust));
        
        string IMigrationMetadata.Id
        {
            get { return "201712051452293_ajust"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
