// <auto-generated />
namespace T4c.Banco.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class StatusFinanciamento : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StatusFinanciamento));
        
        string IMigrationMetadata.Id
        {
            get { return "201712050359511_StatusFinanciamento"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
